version: '3'
services:
  db:
      image: postgres
      environment:
        - POSTGRES_DB=giftcards
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: bash -c "python ./giftcardshop/manage.py migrate && python ./giftcardshop/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db