# Generated by Django 3.0.7 on 2020-06-13 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200613_1838'),
        ('giftcards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftcard',
            old_name='purchase_amount',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='available',
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='description',
        ),
        migrations.AddField(
            model_name='giftcard',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Order'),
        ),
    ]
