# Generated by Django 3.0.7 on 2020-06-14 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_paid'),
        ('giftcards', '0002_auto_20200613_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Order'),
        ),
    ]
