# Generated by Django 3.0.7 on 2020-06-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0003_auto_20200614_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
