# Generated by Django 3.0.7 on 2020-06-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0004_auto_20200615_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
