# Generated by Django 3.0.8 on 2020-07-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='outdated',
            field=models.BooleanField(default=False),
        ),
    ]
