# Generated by Django 3.0.7 on 2020-06-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_auto_20200613_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
